package com.d4rk.cleaner.constants.error

enum class ErrorType {
    STORAGE_PERMISSION,
    ANALYSIS_ERROR,
    CLEANING_ERROR,
    APP_LOADING_ERROR,
    APK_INSTALLATION_ERROR,
    APK_SHARING_ERROR,
    APP_SHARING_ERROR,
    APP_INFO_ERROR,
    APP_UNINSTALLATION_ERROR,
    STORAGE_INFO_ERROR,
    RAM_INFO_ERROR,
    STORAGE_BREAKDOWN_ERROR,
    UNKNOWN_ERROR,
}