package com.d4rk.cleaner.constants.datastore

object DataStoreNamesConstants {
    const val DATA_STORE_SETTINGS = "settings"
    const val DATA_STORE_LAST_USED = "last_used"
    const val DATA_STORE_STARTUP = "startup"
    const val DATA_STORE_THEME_MODE = "theme_mode"
    const val DATA_STORE_AMOLED_MODE = "amoled_mode"
    const val DATA_STORE_DYNAMIC_COLORS = "dynamic_colors"
    const val DATA_STORE_BOUNCY_BUTTONS = "bouncy_buttons"
    const val DATA_STORE_STARTUP_PAGE = "startup_page"
    const val DATA_STORE_SHOW_BOTTOM_BAR_LABELS = "show_bottom_bar_labels"
    const val DATA_STORE_LANGUAGE = "language"
    const val DATA_STORE_GENERIC_FILTER = "generic_filter"
    const val DATA_STORE_DELETE_EMPTY_FOLDERS = "delete_empty_folders"
    const val DATA_STORE_DELETE_ARCHIVES = "delete_archives"
    const val DATA_STORE_DELETE_INVALID_MEDIA = "delete_invalid_media"
    const val DATA_STORE_DELETE_CORPSE_FILES = "delete_corpse_files"
    const val DATA_STORE_DELETE_APK_FILES = "delete_apk_files"
    const val DATA_STORE_DELETE_AUDIO_FILES = "delete_audio_files"
    const val DATA_STORE_DELETE_VIDEO_FILES = "delete_video_files"
    const val DATA_STORE_DELETE_IMAGE_FILES = "delete_image_files"
    const val DATA_STORE_CLIPBOARD_CLEAN = "clipboard_clean"
    const val DATA_STORE_USAGE_AND_DIAGNOSTICS = "usage_and_diagnostics"
    const val DATA_STORE_ADS = "ads"
}