[versions]
agp = "8.8.0"
coilVideoVersion = "3.0.4"
compressor = "3.0.1"
aboutlibraries = "11.3.0"
constraintlayoutCompose = "1.1.0"
kotlin = "2.0.21"
google-services = "4.4.2"
koin = "4.0.1"
google-firebase-crashlytics = "3.0.3"

[libraries]
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
coil3-coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilVideoVersion" }
compressor = { module = "id.zelory:compressor", version.ref = "compressor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googlePlayServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
googleFirebase = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }

[bundles]
koin = [
    "koin-core",
    "koin-compose-viewmodel",
    "koin-android"]
